In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [7]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.arange(0,10)

In [6]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr = np.linspace(1,5, 25)
print(arr)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [14]:
arr = np.logspace(1,12,6)
print(arr)

[1.00000000e+01 1.58489319e+03 2.51188643e+05 3.98107171e+07
 6.30957344e+09 1.00000000e+12]


In [16]:
arr = np.zeros([2,3])
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr = np.ones([3,2], dtype= int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [23]:
arr = np.random.rand(10)
arr

array([0.29445309, 0.38767552, 0.27428904, 0.72873899, 0.91633238,
       0.39950391, 0.835169  , 0.70022629, 0.76188987, 0.48177978])

In [31]:
arr = np.random.randint(1,100, size = (2,6))
arr

array([[81, 34, 16, 76,  6, 78],
       [19, 86, 81, 76, 48, 69]], dtype=int32)